# Generated by Django 4.2 on 2023-04-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("peso", models.IntegerField()),
                ("old", models.IntegerField()),
                ("disease", models.CharField(max_length=3)),
            ],
        ),
    ]
